project_id = "sqvaqiepymfoubwibuds"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[functions.ai-enhance-resume]
verify_jwt = true

[functions.generate-resume-pdf]
verify_jwt = true

[functions.create-payment]
verify_jwt = true

[functions.check-user-plan]
verify_jwt = true

[functions.enhanced-check-user-plan]
verify_jwt = true

[functions.enhanced-create-payment]
verify_jwt = true

[functions.ai-enhance-content]
verify_jwt = true

[functions.export-resume]
verify_jwt = true

[functions.stripe-webhooks]
verify_jwt = false

[functions.customer-portal]
verify_jwt = true