services:
  - type: web
    name: novacv-backend
    env: node
    plan: starter
    rootDir: backend
    buildCommand: npm install --production
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_VERSION
        value: v1
      - key: PORT
        value: 10000
      - key: PAYMENTS_PROVIDER
        value: paddle
      # Required: Add these in Render Dashboard Environment Variables
      # - SUPABASE_URL (required)
      # - SUPABASE_SERVICE_ROLE_KEY (required)
      # - JWT_SECRET (required)
      # - PADDLE_API_KEY (required)
      # - PADDLE_BASIC_PLAN_ID (required)
      # - PADDLE_PRO_PLAN_ID (required)
      # Optional environment variables:
      # - PADDLE_ENVIRONMENT (default: sandbox)
      # - PADDLE_WEBHOOK_SECRET (optional)
      # - FRONTEND_URL (optional)
    healthCheckPath: /api/v1/health
    auto-deploy: false
